export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 text-text-muted leading-relaxed">
      <div className="space-y-3 pb-6 border-b border-border">
        <span className="text-xs font-bold uppercase tracking-wider text-text-accent">
          Legal Notice
        </span>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-text-primary font-display">
          Platform Disclaimer
        </h1>
        <p className="text-xs text-text-muted">Last Updated: September 11, 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-text-primary">1. Valuation & Estimator Disclaimer</h2>
        <p className="text-sm">
          Vehicle valuation estimates generated by our Pricing Tools are algorithmic estimations derived from historical marketplace sales and regional market trends. They do not constitute a formal appraisal or a guaranteed purchase offer price by C2C Motors.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-text-primary">2. Vehicle Condition & Inspection Disclaimer</h2>
        <p className="text-sm">
          While certified 200-point inspection reports provide comprehensive physical diagnostic evaluations at the specific time of inspection, C2C Motors does not warrant against post-inspection vehicle wear, latent mechanical failures, or unauthorized seller modifications made following the inspection date.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold text-text-primary">3. Third-Party Links & Financial Lenders</h2>
        <p className="text-sm">
          Financing calculators and lender options displayed on our platform are provided for informational convenience. Credit approvals, interest rates, and loan terms are determined independently by partner financial institutions. C2C Motors is not a licensed credit broker.
        </p>
      </section>
    </div>
  );
}
